name: GridDemo CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium-chrome:
        image: selenium/standalone-chrome:4.21.0
        ports:
          - 4444:4444
        options: --shm-size=2g

      selenium-firefox:
        image: selenium/standalone-firefox:4.21.0
        ports:
          - 4445:4444
        options: --shm-size=2g

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and run tests
        run: clean test -DsuiteFile=testng.xml

